# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Cloud-Toolchain
tagline:          'Tooling is life'
description:      'Helping Dev Teams in Shuttertstock with Tooling'
url:              https://toonjohners.github.io/docs/
baseurl:          https://toonjohners.github.io/docs/
site:             https://toonjohners.github.io/docs/

author:
  name:           'John McCormack'
  url:            blah

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/toonjohners/docs
